### ISSUE TITLE
Two-Note-Hold keyswitch only holds one note

### ISSUE THREAD

**Issue by Schroedingers-Cat** [jtackaberry/reaticulate#26]
Currently, two-note-hold keyswitches do not work, as the first note (48) is interpreted as a simple note with an immediate note-off event. The synthax used is:
```
o=note-hold:48,127/note-hold:36,127
```

Keyswitches like these are used by Sample Modeling. Holding C2 basically remaps the keyswitches from C1-B1 like this:  
![grafik](https://user-images.githubusercontent.com/6382400/35659740-be294120-06bc-11e8-8a1e-0393c922bcd3.png)

**Comment by jtackaberry** [comment]
It's not that the first note is interpreted as a normal note (with note-off), but it's that the processing of the second note-hold event causes the note-off of the first event to be sent.  It's a subtle difference, but I suppose the net result *looks* the same. :)

This is related to #20, though that deals with note output types rather than note-hold.  I'll be updating both note and note-hold output types with the following behaviors:
* note: all note-off MIDI events for a list of note outputs will occur only after the note-on events have been sent for all notes in the output list.
* note-hold: no note-off will be sent during processing the output event list.  When another articulation is activated, only then will all held notes (recognizing there may be more than one -- that was my mistake) be released with note-off events.

Thanks for the report!
