### ISSUE TITLE
Reaticulate doesn't start on a portable install of Reaper

### ISSUE THREAD

**Issue by SimoneLocatelli** [jtackaberry/reaticulate#46]
Whenever I try to run the startup script, I get this error message:
`
...Reaper\Scripts\Reaticulate\actions\**Reaticulate_Start**.lua:20: bad argument #1 to 'ReverseNamedCommandLookup' (number expected, got nil)`

Opening the script we're got these two lines:
```

cmd = reaper.GetExtState("reaticulate", "main_command_id")
        if not cmd or not reaper.ReverseNamedCommandLookup(tonumber(cmd)) then
```

For whatever reason, **GetExtState** doesn't return a number, rather a _nil_ value

Any idea how to this issue?

**Comment by SimoneLocatelli** [comment]
That's it, thanks a lot!
It could be a good idea to mention it on the site, it may be useful to others as well

**Comment by jtackaberry** [comment]
The First Run instructions on the site do say to run Reaticulate_Main.lua so I'm not sure if updating the site would help.  Rather than erroring out, the current code (not yet committed) will popup a message box informing the user to run Reaticulate_Main manually, so that's probably good enough to address it outside of the documentatino.
