### ISSUE TITLE
Make articulation insertion compatible with undo

### ISSUE THREAD

**Issue by Levitanus** [jtackaberry/reaticulate#47]
I think it's consolidated with something else. When articulation is added by right-clicking, then immediately record starts, and after it undo is used, both, the recorded midi and pr change are removed.

**Comment by jtackaberry** [comment]
I can't reproduce this exactly, but there's always not been something quite right about the how Reaper handles undo with Reaticulate.  It's something I've wrestled with, and I'm quite convinced there is at least one Reaper bug at play here, because despite neatly wrapping everything in Undo_BeginBlock2() and Undo_EndBlock2(), initiating an undo in Reaper will sometimes undo beyond the point of the Undo_BeginBlock2() call.

**Comment by Levitanus** [comment]
Yep, I've also noticed at my scripts)
Still, I found a way of selecting the item between art assignment and record start. Not hard to keep in practice and works

**Comment by jtackaberry** [comment]
The redesign described by #62 will open the door to workarounds.  I have a proof of concept working in my local tree so I'll tentative plan to fix this in the next major release (0.4.0).
