### ISSUE TITLE
Allow user customizable MIDI data to be sent to control surface on track select

### ISSUE THREAD

**Issue by jtackaberry** [jtackaberry/reaticulate#70]
To better support more sophisticated control surface use-cases that present different pages based on available articulations, Reaticulate should allow users to specify custom MIDI data to be emitted to the control surface upon track select.

Reaper's Lua API only allows stuffing conventional 3-byte messages, so doing this properly will require enlisting help from the RFX, which can use `midisend_buf()`.

This will depend on gmem support from #62.  We'll create another opcode for sending a buffer to the control surface in the next `@block` which the main script will invoke in `feedback.ontrackchange()` if feedback is enabled.  This buffer will need to be persisted in the per-RFX appdata, but because appdata is opaque to the RFX, it will still be necessary to send it with the opcode.

**Comment by Phfraiengngchkxzcs** [comment]
This is fantastic. I have spent a few days setting up a lemur controller to trigger Reaticulate. Compared to the version I've seen for Cubase, Reaticulate makes this much easier. However, i'm realizing the potential limitation of triggering the automatic update of the pads in lemur via Bank Change information sent out on CC 32 is that it's going to be limited to 127 Banks which will accommodate triggering of 127 different instrument maps before the cycle repeats it self. 

There might be a way to solve this in Lemur, but i'm new to the scripting. by choosing different MIDI channels for different banks of sounds. E.g., strings = channel 1 bank change 1-127 ( for each distinct string articulation map needed), brass = channel 2 bank change 1-127. But, i can't figure out how to make lemur get that info back from it's own trigger. if you change the channels for the instrument in Reaticulate, a midi monitor in lemur will show the change. So, a clicking on each articulation will generate, for example, {32,1,0} for an instrument set to omni or midi channel 1 and bank 01 in Reaticulate. setting an instrument to MIDI channel 16, Bank 01 will generate a response of {32,1,15}. So, in Lemur i set up 2 arguments, bank=MIDI_ARGS[1] for the CC data coming from CC32 and chan=MIDI_ARGS[2] to try to pick up the changes in the channels being sent out.  However, when i then try to use Lemur to change the articulations of that patch on channel 16, the monitor returns to {32,1,0} and the articulation map jumps back to the patch loaded for Channel 1 Bank 1. Maybe someone can tell me if i'm doing something wrong on the Lemur side. It's close to working. Here's a quick video of my setup showing Lemur controlling Channel 1 Bank 1 (Berlin Violin I), then jumping to Channel 16 Bank 1 (arbitrarily set to LASS Violin I). you can see the midi monitor change channels but then when i hit the pads on Lemur, the pads jump back to the configuration for Chan 1 (Berlin) and the monitor changes to {32,1,0} so that the pads and the Reaticulate bank no longer match. 
![Uploading Screen Shot 2019-07-19 at 3.14.20 PM.png…]()
![Uploading Screen Shot 2019-07-19 at 3.14.34 PM.png…]()
![Uploading Screen Shot 2019-07-19 at 3.14.49 PM.png…]()

**Comment by jtackaberry** [comment]
Not very clueful when it comes to Lemur (haven't used it yet), so trying to wrap my head around your configuration and challenges.

Can you expand a bit more on the MIDI events that Lemur sends out when you activate an articulation from the control surface, and how you've set up the bindings from those events to Reaticulate's actions in Reaper's action list?

**Comment by Phfraiengngchkxzcs** [comment]
thanks so much for the very quick response! reaticulate is amazing! it's totally changed my workflow. and yes, i'd be happy to clarify. 

it really is so much simpler than the awesome and complicated setup i'm sure you've seen from Mihkel Zilmer for Cubase. Like most people i've seen in the forums, i started there and reverse engineered. However, I basically just have lemur setup to to receive the Bank Change messages that Reaticulate sends out on CC32 per your online instructions. You can see this in Screen Shot 4 below. in the picture i've just told Lemur to call "MIDI_ARGS[1]" the "bank" (which is the bank # it's receiving on CC32)
 MIDI_ARGS[0]= the CC#, MIDI_ARGS[1]=Bank Message, MIDI_ARGS[2]=the channel.) So, what you see in the picture is I tell lemur, when it receives a Bank # = to 1 to then choose Bank 1 from my Pad setup. Therefore, it auto-populates the pads with the correct articulations for Berlin Violin I in my setup. Bank 2 (which Lemur gets when i click on the track for Violin 2, which returns MIDI_ARGS {32,2,0} for CC 32, Bank 2, Channel 1 (Lemur starts at 0, so chn 1-16 are 0-15) and auto populates the articulations for Berlin Violin II. On the right side of the screen you can see the abbreviations for all the articulations i've mapped so far. Lemur uses those abbreviations to then fill the pads with the correct labels. 

Lemur is currently only sending program change info. 0-127. reaticulate receives the program change and triggers the articulations based on the setup in Reaticulate.reabank. 

In Screen Shots 5 & 6 Below you can see how simple the output is. "PC_out" is sending Program Change info on MIDI Port 0 (my primary Lemur MIDI port). There is a very small script used that i slightly altered from Mihkel's template that sets PCout: PC_out=firstof(x)+1; which simply means that when you press a pad on Lemur, the X Value of that pad (0-127) is then sent to PC-out and simply translated to Program Change info. I changed it to (x)+1 because x starts at 0. so pads 0-127 send out 1-128 PC data to Reaticulate, which interprets it extremely quickly and fluidly. 

the only challenge is that without figuring out how to use more than just the 0-127 Bank Change CC info sent out on CC32, one is limited to 127 articulation maps. And when thinking about say, Violin I & II, Viola, Cello Bass for 5 main libraries, you've already burned 25 maps. Brass, Winds, Percussion, Choir, plus any specialty things, solo strings, solo brass, etc... I think people with large templates are going to run out of maps. 

My thought was to somehow get Lemur to read the Channel Information that is generated if you change the Reaticulate-Out channel away from "Source" and use a distinct MIDI Channel (my experience has been that the source has to be set to Omni for Lemur and Reaticulate to talk) so that i can alter the argument for choosing the instrument map in Lemur. 

for example. instead of "if bank==01 then choose String Bank 1" something using 2 arguments like "if bank+chn={01,15} then choose brass bank x... etc... having a second argument would allow for a greater variety of bank selections. 

perhaps this is already possible and it's my very limited Lemur skills causing the issue. i Hope this makes some sense. Thanks again for the quick response!

<img width="1573" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/50972711/61570192-f2856200-aa3f-11e9-83e1-e91197076d83.png">
<img width="456" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/50972711/61570193-f2856200-aa3f-11e9-91de-39a37b04c9de.png">
<img width="1555" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/50972711/61570194-f31df880-aa3f-11e9-9209-0d46b99a0aea.png">

**Comment by jtackaberry** [comment]
> the only challenge is that without figuring out how to use more than just the 0-127 Bank Change CC info sent out on CC32, one is limited to 127 articulation maps. 

Reaticulate does send out a 14-bit Bank select event, which would allow up to over 16,000 different banks.  In practice, a 14-bit bank select will be a CC0 (containing the MSB of the bank) followed by a CC32 (containing the LSB).

If Lemur is able to process a 14-bit Bank select then you could just compare both MSB and LSB to set the appropriate bank on the Lemur side.  If it can only handle 7-bit CCs, then you might be able to process CC 0 (which Reaticulate will send first) and store MIDI_ARGS[1] as a global variable (hopefully Lemur has such a construct?), and then when CC 32 comes along, the code you're showing Screenshot 4 can look at MIDI_ARGS[1] from the CC 32, along with the stored value from the previous CC 0.

This way you shouldn't have to play any tricks with dividing up your MIDI channels.

**Comment by jtackaberry** [comment]
@Phfraiengngchkxzcs  another challenge is that the bank select message is only sent out by Reaticulate when an articulation is activated.  So changing tracks won't cause your control surface to update.  That capability is what issue #70 here is tracking: being able to send out some MIDI to the control surface when the selected track changes.

**Comment by Phfraiengngchkxzcs** [comment]
Thank you so much, Tack! This is great. I am about 5 days into working with Lemur so it sounds like it's my ignorance. I don't yet know how to make Lemur listen for both the MSB and LSB but I'm sure it can. Just need to figure out how to tell it to do so. 
And  regarding issue #70, that will be a nice addition for sure. Though I'm not finding that it's currently a major hinderance. I have a Track Up/Track Down button to change tracks or just click on the computer screen. a quick touch of the iPad screen will populate the correct articulations. It'll be nice to be able to see those instantaneously but it still works pretty well as far as that's concerned. Thanks, again!

**Comment by Phfraiengngchkxzcs** [comment]
by the way, if i'm getting both the MSB and LSB, should it be reading those from the Reabank script. in screenshot 7 below, i have my Cello Extensions bank set as 51 8. Right now Lemur is only getting the 8. it sees 32,8,0. I'm curious if it's supposed to be seeing 0,51,0 as well as 32,8,0. i'll keep reading. just very foreign to the scripting side of things. 
<img width="730" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/50972711/61581882-1cd72e00-aad9-11e9-882c-ca9eeca30ee6.png">

**Comment by jtackaberry** [comment]
> I don't yet know how to make Lemur listen for both the MSB and LSB but I'm sure it can.
The way I'd do this with Bome MIDI Translator is the way I mentioned: handle CC0 first, store the value in a global variable, then in the CC32 handler, refer to the CC32 value (LSB) and the stored value from CC0.  How to do this in Lemur I can't say, unfortunately.  Good luck.

I actually tried to get Lemur but it looks like it's been discontinued to blacklisted on Android (Liine's website's link to the Android version is broken) and I don't own any iOS products.

**Comment by jtackaberry** [comment]
> I'm curious if it's supposed to be seeing 0,51,0 as well as 32,8,0
Yup, definitely.

If you want to prove it to yourself:
1. open Reaper's Track Manager (`View | Track Manager`)
2. find the `MIDI Feedback (Reaticulate)` track in the list
3. click the cell in the TCP column to make it visible in the TCP
4. Right click the track and MIDI Feedback track in the TCP and select `MIDI Track Controls | Show MIDI Track Control Panel`
5. Move the ReaControlMIDI FX that was just added to the track's FX list *after* the `Feedback Translator` FX that's already there
6. In the ReaControlMIDI instance, click `Show Log`
7. Activate an articulation on some track

You should see separate CC0 and CC32 events in the MIDI log.

**Comment by Phfraiengngchkxzcs** [comment]
damn, that's annoying! seems like the Windows download will work but not the Android.

**Comment by Phfraiengngchkxzcs** [comment]
<img width="1565" alt="Screen Shot 2019-07-20 at 10 44 14 AM" src="https://user-images.githubusercontent.com/50972711/61582107-66c11380-aadb-11e9-8c51-fd329504c6a5.png">
awesome! thanks! seems like that is working. although you said the "MIDI Feedback Track". i have numerous Tracks. did i set that up incorrectly? i just added the reaticulate to each track and looking in the Track Manager this is what i see.

**Comment by jtackaberry** [comment]
> although you said the "MIDI Feedback Track". i have numerous Tracks. did i set that up incorrectly? i just added the reaticulate to each track and looking in the Track Manager this is what i see. 

Oh, wow, something went wrong here. :)

You should only ever have one such "MIDI Feedback (Reaticulate)" track.  Reaticulate creates this automatically and its job is to manage it.  There is definitely a bug in Reaticulate here.

Can you confirm what version you're running?  You can check via the menu `Extensions | ReaPack | Browse Packages` and searching for Reaticulate, assuming you did install it via the ReaPack method.

**Comment by Phfraiengngchkxzcs** [comment]
i'm running 0.3.1 it looks like.

**Comment by Phfraiengngchkxzcs** [comment]
yeah, it hasn't seemed to be buggy as far as function goes, but i noticed that the other day and wondered if maybe i had done something wrong.

**Comment by jtackaberry** [comment]
> yeah, it hasn't seemed to be buggy as far as function goes, but i noticed that the other day and wondered if maybe i had done something wrong.

Nah this is definitely a bug.  I'll take a look at the code and see if I can suss out what condition might have caused that, and in any case can add some logic to make it more robust.

Meanwhile feel free to delete those other feedback tracks via the Track Manager.

**Comment by Phfraiengngchkxzcs** [comment]
ah, ha! i had a piece of code that was telling my Lemur MIDI_In Monitor to only look in one place for the CC Data. one step closer. Lemur is now reading the MSB and LSB. i just set my LASS Bank to 81 arbitrarily and kept my Berlins at 51. (Screenshots 8&9) 

setup a monitor for both CC0 and CC32 and they are reading it correctly. I'm not sure what the 85 and 14 are in the {81,85,14} vector. are those possibly the noteoff and program change #s being sent (screenshot 10)

<img width="273" alt="Screen Shot 10" src="https://user-images.githubusercontent.com/50972711/61582604-b276bb80-aae1-11e9-8df3-4c26009d02cb.png">
<img width="2140" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/50972711/61582605-b276bb80-aae1-11e9-84b7-d0aa86b9fcdf.png">
<img width="2166" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/50972711/61582606-b276bb80-aae1-11e9-931e-294b291030d9.png">

**Comment by Phfraiengngchkxzcs** [comment]
great, deleted all of them. there were about 40. function is good with just the 1.

**Comment by jtackaberry** [comment]
> there were about 40. function is good with just the 1.

If you happen to figure out what interaction is causing more of them to show up, please open a new issue. :)

**Comment by Phfraiengngchkxzcs** [comment]
will do. i'll keep an eye on that.

**Comment by jtackaberry** [comment]
> I'm not sure what the 85 and 14 are in the {81,85,14} vector. are those possibly the noteoff and program change #s being sent (screenshot 10)

Good question.  I can't quite see where it's getting 85 and 14 from either.

The note-off event looks like a bug to me.  But it shouldn't be hurting anything either.

**Comment by jtackaberry** [comment]
@Phfraiengngchkxzcs  BTW what Reaper theme are you using?

**Comment by jtackaberry** [comment]
> @Phfraiengngchkxzcs another challenge is that the bank select message is only sent out by Reaticulate when an articulation is activated. So changing tracks won't cause your control surface to update.

I tell a lie.  Actually Reaticulate 0.3.1 does send out the currently selected articulation when the track is selected.  So this issue here is just to allow customization of MIDI event data.

Also, I looked at the code, and the note-off isn't a bug.  It's intentional: I'm using the note-off event for note 0 to encode the articulation group before the program change event.  The velocity of the note-off indicates the group number.  The real bug is that this isn't documented. :)

**Comment by Phfraiengngchkxzcs** [comment]
using Reaper 5.980

**Comment by jtackaberry** [comment]
> using Reaper 5.980

No I meant your theme.

**Comment by Phfraiengngchkxzcs** [comment]
oh, sorry. i misread. i am using a theme that a friend of mine tweaked. it's labeled "Default_commala_5_2016".

**Comment by Phfraiengngchkxzcs** [comment]
<img width="821" alt="Screen Shot 11" src="https://user-images.githubusercontent.com/50972711/61583131-b65a0c00-aae8-11e9-8ef5-b89e677a62a5.png">

made a slight alteration to the script i've been working from. it makes logical sense but i'm not totally sure how to test it. i set up a MIDI CC0 script that just receives that midi, and a MIDI cc32 script. called those a and b. then set my "pc" selector to be triggered by receiving the MSB and LSB from those 2 CC channels. It didn't break the script but i'm not sure if it changed much. all articulations seem to be working correctly no matter what i do. I tried changing the bank in reaticulate to 81 for some patches, without updating that in the script and even though the monitor says it's getting (for example) 81,15 the articulations are still being mapped accurately. even though the script is looking for 51,15. so there's something going on behind the scenes that i'm not getting. But i think something like this will work.

**Comment by Phfraiengngchkxzcs** [comment]
hi Tack, wanted to give you an update on the thing you noticed yesterday with the Reaticulate Feedback. since removing all of the additional tracks, no new ones have been generated. However, when I opened up my session today I got this error message. I  get this message every time i try to open the Reaticulate editor. 
<img width="1055" alt="Screen Shot 2019-07-21 at 1 03 18 PM" src="https://user-images.githubusercontent.com/50972711/61596405-0b188800-abb8-11e9-8ac0-baea0055c104.png">

**Comment by Phfraiengngchkxzcs** [comment]
Hi Tack! I got Reaticulate working fully with Lemur. I'm such a noob that I didn't understand how simple and elegant it is. Works fantastically! the CC0/32 setup is awesome and so powerful. Don't think I'll ever need more than 16,000 instrument maps. When I get closer to having this fully setup with all my banks loaded, I'll post screenshots or a walkthrough for folks. I've seen a bunch of forum posts asking about this. so pumped!

**Comment by jtackaberry** [comment]
> However, when I opened up my session today I got this error message. I get this message every time i try to open the Reaticulate editor.

Hm, that's a surprising error.  Based on my reading of the code that shouldn't happen.  Absent understanding what's actually happening here, I'll code things a bit more defensively.

> I got Reaticulate working fully with Lemur.

That's great to hear @Phfraiengngchkxzcs !

**Comment by Phfraiengngchkxzcs** [comment]
Hi @jtackaberry, just ran into another quirk. not sure if it's a bug or just something weird in my setup. curious if it rings any bells. i'm setting up all my articulation maps and found that 1 instrument is causing problems. Spitfire Solo French Horn. For some reason, no matter what articulation i press (either in reaticulate or from Lemur, the Legato patch remains in effect. so i get Legato+marcato, etc.. no other spitfire stuff is behaving this way but this one. tried locking to UACC or UACC KC but then no sound plays until you select a new articulation and that can only happen from Reaticulate. Lemur stops working entirely. it's odd.

**Comment by jtackaberry** [comment]
>  Spitfire Solo French Horn. For some reason, no matter what articulation i press (either in reaticulate or from Lemur, the Legato patch remains in effect. so i get Legato+marcato, etc.. no other spitfire stuff is behaving this way but this one.

@Phfraiengngchkxzcs this sounds more like a problem with the Spitfire patch than Reaticulate, where the patch has some weird initial state.  You can confirm that Reaticulate is sending the correct MIDI by inserting a ReaControlMIDI instance with logging enabled after Reaticulate.  FWIW, I don't see this with the Spitfire Symphonic Brass solo horn.  (Maybe you're talking about the Studio series?)

If this is a custom bank, can you please open a new issue to discuss and include the bank definition and patch details?  This discussion really has veered away from this issue which is to allow user MIDI data to be sent to a control surface when tracks are changed.

**Comment by Phfraiengngchkxzcs** [comment]
you bet. thanks! you've been so helpful.

**Comment by jtackaberry** [comment]
Implemented in 33cc950

**Comment by Phfraiengngchkxzcs** [comment]
Awesome! Thank you very much, Jason! Looking forward to playing with this this week!

Ryan Franks
(323) 333-6778
RSBrigade<http://rsbrigade.com>
IMDB<http://www.imdb.com/name/nm1766391/>






On Sep 12, 2022, at 12:56 PM, Jason Tackaberry ***@***.******@***.***>> wrote:



Closed #70<https://github.com/jtackaberry/reaticulate/issues/70> as completed.
